version: '3.9'

services:
  pyspark:
    container_name: pyspark
    build:
      context: ..
      dockerfile: ./docker/pyspark.Dockerfile
      args:
        - USER_NAME=spark
        - USER_ID=${USER_ID}
    volumes:
      - ../data-pipeline/pyspark/:/pyspark:rw
    working_dir: /pyspark
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      SPARK_MASTER_HOST: ${SPARK_MASTER_HOST}
      SPARK_MASTER_PORT: ${SPARK_MASTER_PORT}
    restart: unless-stopped
    # depends_on:
    #   - mosquitto
    #   - kafka
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../mosquitto/passwd:/mosquitto/config/passwd
      - ../mosquitto/logs:/mosquitto/logs
    ports:
      - "1883:1883"
    restart: unless-stopped

  # zookeeper:
  #   container_name: zookeeper
  #   image: zookeeper:3.8.1
  #   restart: unless-stopped

  # kafka:
  #   container_name: kafka
  #   image: wurstmeister/kafka:2.13-2.8.1
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     DOCKER_API_VERSION: 1.22
  #     KAFKA_ADVERTISED_HOST_NAME: kafka.docker
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped
  #   depends_on:
  #     - zookeeper

  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_RETENTION: 3d
    ports:
      - "8086:8086"
    restart: unless-stopped

  telegraf:
    container_name: telegraf
    image: telegraf:1.26-alpine
    environment:
      INFLUX_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
    depends_on:
      - influxdb
