version: '3.9'

services:
  pyspark:
    container_name: pyspark
    build:
      dockerfile: pyspark.Dockerfile
    volumes:
      - ../data-pipeline/pyspark/:/pyspark:rw
    working_dir: /pyspark
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ../data-pipeline/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883"
