version: '0.1'
services:
  pyspark:
    container_name: pyspark
    network_mode: "host"
    tty: true
    stdin_open: true
    build: 
      context: ..
      dockerfile: ./docker/pyspark.Dockerfile
      args:
        - USER_NAME=spark
    volumes:
      - ../pyspark/:/app/pyspark:rw
    working_dir: /app/pyspark

  mosquitto:
    container_name: mosquitto
    network_mode: "host"
    image: eclipse-mosquitto
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
